# generator/topics.py
"""
Спільний список тем рівня A1, який використовують:
  - bot/handlers.py     (ручна /generate, /regenerate_day_)
  - bot/scheduler.py    (автогенерація наступного дня наприкінці вечірньої публікації)

Винесено в окремий модуль, щоб уникнути дублювання списку та
циклічного імпорту (bot/handlers.py вже імпортує bot/scheduler.py,
тому scheduler.py не може імпортувати щось із handlers.py напряму).
"""

DEFAULT_TOPICS = [
    {"ua": "Знайомство та привітання", "es": "Saludos y presentaciones"},
    {"ua": "Числа від 0 до 100", "es": "Los números del 0 al 100"},
    {"ua": "Дні тижня та місяці", "es": "Los días de la semana y los meses"},
    {"ua": "Пори року та погода", "es": "Las estaciones y el tiempo"},
    {"ua": "Кольори та форми", "es": "Los colores y las formas"},
    {"ua": "Сім'я та родичі", "es": "La familia y los parientes"},
    {"ua": "Опис зовнішності та характеру", "es": "Descripción física y de carácter"},
    {"ua": "Професії та діяльність", "es": "Las profesiones y los oficios"},
    {"ua": "Країни та національності", "es": "Países y nacionalidades"},
    {"ua": "Вираження причини та наслідку", "es": "Expresar causa y consecuencia"},
    {"ua": "У лікаря та в аптеці", "es": "En el médico y en la farmacia"},
    {"ua": "Близьке майбутнє (конструкція Ir a)", "es": "El futuro próximo con ir a"},
    {"ua": "Музика та мистецтво", "es": "La música y el arte"},
    {"ua": "Пошук роботи, резюме та співбесіда", "es": "La búsqueda de empleo, el currículum y la entrevista"},
    {"ua": "Погода у деталях та стихійні лиха", "es": "El tiempo en detalle y los desastres naturales"},
    {"ua": "Вступні слова та зв'язки (проте, крім того, отже)", "es": "Conectores del discurso y marcadores textuales"},
    {"ua": "Транспорт та квитки", "es": "El transporte y los billetes"},
    {"ua": "Іспанські ідіоми та фразеологізми", "es": "Modismos y expresiones idiomáticas"},
    {"ua": "Мій дім та квартира", "es": "Mi casa y mi piso"},
    {"ua": "Автомобіль, будова та ремонт авто", "es": "El coche, sus partes y la reparación de automóviles"},
    {"ua": "Простий минулий час (Indefinido)", "es": "El pretérito indefinido en español"},
    {"ua": "Одяг та взуття", "es": "La ropa y el calzado"},
    {"ua": "Покупки та супермаркет", "es": "Las compras y el supermercado"},
    {"ua": "Вираження згоди та незгоди", "es": "Expresar acuerdo y desacuerdo"},
    {"ua": "Програмування, IT та робота з комп'ютером", "es": "La programación, la informática y el trabajo con ordenadores"},
    {"ua": "Умовний спосіб (Condicional Simple)", "es": "El condicional simple en español"},
    {"ua": "Розпорядок дня", "es": "La rutina diaria"},
    {"ua": "Подорожі та відпочинок", "es": "Los viajes y las vacaciones"},
    {"ua": "Популярні розмовні сленгові вирази", "es": "Jerga y expresiones populares"},
    {"ua": "Теперішній час в іспанській", "es": "El presente de indicativo en español"},
    {"ua": "Ресторанні страви, спеції та смаки", "es": "Platos de restaurante, especias y sabores"},
    {"ua": "Фінанси, банківські рахунки та кредити", "es": "Finanzas, cuentas bancarias y créditos"},
    {"ua": "Прохання про допомогу та дозвіл", "es": "Pedir ayuda y permiso"},
    {"ua": "Емоції та почуття", "es": "Las emociones y los sentimientos"},
    {"ua": "Місто та його інфраструктура", "es": "La ciudad y la infraestructura"},
    {"ua": "Університет, лекції та іспити", "es": "La universidad, las conferencias y los exámenes"},
    {"ua": "Теперішній суб'юнктив (Presente de Subjuntivo)", "es": "El presente de subjuntivo en español"},
    {"ua": "Природа та навколишнє середовище", "es": "La naturaleza y el medio ambiente"},
    {"ua": "Вибачення та реакція на них", "es": "Disculpas y cómo reaccionar"},
    {"ua": "Тварини (домашні та дикі)", "es": "Los animales (domésticos y salvajes)"},
    {"ua": "Побутова техніка", "es": "Los electrodomésticos"},
    {"ua": "Простий майбутній час (Futuro Simple)", "es": "El futuro simple en español"},
    {"ua": "Здоров'я та самопочуття", "es": "La salud y el estado físico"},
    {"ua": "Кохання, романтичні стосунки та весілля", "es": "El amor, las relaciones románticas y las bodas"},
    {"ua": "Податки, державні служби та бюрократія", "es": "Impuestos, servicios públicos y burocracia"},
    {"ua": "Навчання та школа", "es": "Los estudios y la escuela"},
    {"ua": "Висловлення невдоволення та скарги", "es": "Expresar descontento y reclamaciones"},
    {"ua": "Кулінарні рецепти та приготування їжі", "es": "Recetas de cocina y preparación de platos"},
    {"ua": "Великі числа та рахунок", "es": "Los números grandes y el recuento"},
    {"ua": "Минулий незавершений час (Imperfecto)", "es": "El pretérito imperfecto en español"},
    {"ua": "Орієнтування в місті та напрямки", "es": "Pedir y dar direcciones"},
    {"ua": "Мови світу", "es": "Las lenguas del mundo"},
    {"ua": "Умови та припущення (якщо б...)", "es": "Expresar condiciones e hipótesis"},
    {"ua": "Ремонт та будівництво будинку", "es": "Las reparaciones y la construcción del hogar"},
    {"ua": "В готелі", "es": "En el hotel"},
    {"ua": "Наказовий спосіб (Imperativo)", "es": "El imperativo en español"},
    {"ua": "Меблі та інтер'єр", "es": "Los muebles y la decoración"},
    {"ua": "Аксесуари та прикраси", "es": "Los accesorios y las joyas"},
    {"ua": "Емоційні реакції та вигуки", "es": "Reacciones emocionales y exclamaciones"},
    {"ua": "Ціни та гроші", "es": "Los precios y el dinero"},
    {"ua": "В ресторані та кафе", "es": "En el restaurante y la cafetería"},
    {"ua": "Зовнішній вигляд і стиль одягу", "es": "La apariencia y el estilo de vestir"},
    {"ua": "Минулий завершений час (Pretérito Perfecto Compuesto)", "es": "El pretérito perfecto compuesto en español"},
    {"ua": "Світло, освітлення та електрика в домі", "es": "La luz, la iluminación y la electricidad en casa"},
    {"ua": "Напої", "es": "Las bebidas"},
    {"ua": "Годинник та час", "es": "El reloj y la hora"},
    {"ua": "Вільний час та хобі", "es": "El tiempo libre y las aficiones"},
    {"ua": "Спорт та активність", "es": "El deporte y la actividad física"},
    {"ua": "Кіно, театр та кінематографічні жанри", "es": "Cine, teatro y géneros cinematográficos"},
    {"ua": "Література, книги та письменники", "es": "Literatura, libros y escritores"},
    {"ua": "Архітектура, пам'ятки та історія міста", "es": "Arquitectura, monumentos y la historia de la ciudad"},
    {"ua": "Правила дорожнього руху та штрафи", "es": "Las normas de tráfico y las multas"},
    {"ua": "Подорож автостопом та кемпінг", "es": "El autostop y el camping"},
    {"ua": "В аеропорту та на вокзалі", "es": "En el aeropuerto y la estación"},
    {"ua": "Комахи, плазуни та морські мешканці", "es": "Insectos, reptiles y fauna marina"},
    {"ua": "Екологія, переробка та захист природи", "es": "Ecología, reciclaje y protección del medio ambiente"},
    {"ua": "Земельна ділянка, садівництво та город", "es": "Terreno, jardinería y huerto"},
    {"ua": "Медичні послуги, страхування та лікарні", "es": "Servicios médicos, seguros y hospitales"},
    {"ua": "Аптечні товари, ліки та симптоми", "es": "Productos de farmacia, medicamentos y síntomas"},
    {"ua": "Психічне здоров'я та боротьба зі стресом", "es": "La salud mental y la gestión del estrés"},
    {"ua": "Косметика, догляд за собою та спа", "es": "Cosmética, cuidado personal y spa"},
    {"ua": "Побут у гуртожитку чи оренда житла", "es": "La vida en una residencia de estudiantes o el alquiler de vivienda"},
    {"ua": "Тканини, матеріали та догляд за одягом", "es": "Tejidos, materiales y el cuidado de la ropa"},
    {"ua": "Шкільне та офісне приладдя", "es": "El material escolar y de oficina"},
    {"ua": "Наука, дослідження та технологічні відкриття", "es": "Ciencia, investigación y descubrimientos tecnológicos"},
    {"ua": "Робочий день та офіс", "es": "El día laborable y la oficina"},
    {"ua": "Ділові переговори та офісний етикет", "es": "Negociaciones comerciales y etiqueta de oficina"},
    {"ua": "Свята та традиції", "es": "Las fiestas y las tradiciones"},
    {"ua": "Традиційні фестивалі та національні свята", "es": "Festividades tradicionales y fiestas nacionales"},
    {"ua": "Дні народження та подарунки", "es": "Los cumpleaños y los regalos"},
    {"ua": "Виховання дітей та педагогіка", "es": "La crianza de los hijos y la pedagogía"},
    {"ua": "Міжособистісні конфлікти та їх вирішення", "es": "Conflictos interpersonales y su resolución"},
    {"ua": "Вподобання (що подобається і ні)", "es": "Gustos y preferencias"},
    {"ua": "Географія та сторони світу", "es": "La geografía y los puntos cardinales"},
    {"ua": "Космічний простір, астрономія та Всесвіт", "es": "El espacio exterior, la astronomía y el universo"},
    {"ua": "Технології та гаджети", "es": "La tecnología y los dispositivos"},
    {"ua": "Соціальні мережі та інтернет", "es": "Las redes sociales e internet"},
    {"ua": "Засоби масової інформації, новини та блоги", "es": "Medios de comunicación, noticias y bitácoras"},
    {"ua": "Політика, вибори та державний лад", "es": "Política, elecciones y el sistema de gobierno"},
    {"ua": "Закон, суди та права людини", "es": "La ley, los tribunales y los derechos humanos"},
    {"ua": "Злочини, безпека та поліція", "es": "Delitos, seguridad y la policía"},
    {"ua": "Геополітика та міжнародні відносини", "es": "Geopolítica y relaciones internacionales"},
    {"ua": "Філософські роздуми та сенс життя", "es": "Reflexiones filosóficas y el sentido de la vida"},
    {"ua": "Характер, психологічні типи та темперамент", "es": "Carácter, tipos psicológicos y temperamento"},
    {"ua": "Особисті дані та анкета", "es": "Datos personales y formulario"},
    {"ua": "Плани на майбутнє", "es": "Planes para el futuro"}
]
